Added copy/paste functionality for HierarchyWidget
rockbite/talos pull request #228
Opened 2023-01-13 13:48 UTC by Daeva-Git

2023-01-13 14:43 UTC, vuvkar commented on editor/src/com/talosvfx/talos/editor/addons/scene/SceneEditorWorkspace.java
> +			this.gameAsset = (GameAsset<Scene>) gameAsset;
Did you test this on Prefabs?

2023-01-16 12:52 UTC, vuvkar approved these changes

2023-01-16 13:39 UTC, Tom-Ski requested changes

2023-01-16 13:39 UTC, Tom-Ski commented on editor/src/com/talosvfx/talos/editor/addons/scene/widgets/HierarchyWidget.java
> +    private SavableContainer currentContainer;
Why change this type?

2023-01-17 09:47 UTC, merged