Path Renderer
rockbite/talos pull request #370
Opened 2023-04-05 12:40 UTC by Tatev321

2023-04-05 13:38 UTC, Tom-Ski requested changes

2023-04-05 13:38 UTC, Tom-Ski commented on runtimes/talos/src/main/java/com/talosvfx/talos/runtime/scene/render/PathComponentRenderer.java
> +            Vector2 finalPoint = point.cpy().add(transformComponent.worldPosition);
These points should be pooled rather than cpy

2023-04-05 13:38 UTC, Tom-Ski commented on runtimes/talos/src/main/java/com/talosvfx/talos/runtime/scene/components/PathRendererComponent.java
> +            offsetPoints[idx++] = p.cpy().add(new Vector2(-t.y, t.x).nor().scl(-offsetDistance));
same for here, cpy is gonna be generating a lot of garbage, as well as the New VEctors

2023-04-05 13:38 UTC, Tom-Ski commented on runtimes/talos/src/main/java/com/talosvfx/talos/runtime/scene/components/PathRendererComponent.java
> +        return null;
type should probably be SPRITE

2023-04-06 06:42 UTC, azakhary commented
additionally a change in go-template.xml is required to 
<template name = "curve" title = "Curve" nameTemplate = "Curve" keywords = "">
so that it contains a new component for rendering (which is the defaults on creating new go's

2023-04-06 11:27 UTC, Tom-Ski approved these changes

2023-04-06 11:27 UTC, merged