Unique layers
rockbite/talos pull request #371
Opened 2023-04-10 10:18 UTC by TheSenPie

Added UUID logic for scene layers.
Set preferred layer for GameObjects, when its sorting layer is removed.
Save current state and clear other global states, when layers are modified.
Backward compatibility with old layers format.

[ TODO ]
Improve routines workflow for spawn spine, sprite, particle to use layer uuid instead of name.

2023-04-12 08:27 UTC, Tom-Ski requested changes

2023-04-12 08:27 UTC, Tom-Ski commented on bongo
Bad commits here. .DS_Store shouldn't be commited

2023-04-13 12:33 UTC, TheSenPie commented on bongo
fixed

2023-04-17 10:51 UTC, Tom-Ski approved these changes

2023-04-17 10:51 UTC, merged